### ISSUE TITLE
I need it in java :(

### ISSUE THREAD

**Issue by RayanFar** [benckx/ouistiti#1]
could you please convert it to java source code? I need it but I don't know kotlin...

**Comment by benckx** [comment]
It can be called from Java:
https://github.com/benckx/ouistiti/blob/master/src/test/java/TestCameraManagerJava.java

**Comment by RayanFar** [comment]
just copy that .kt files in my own java package? Does it work?

**Comment by benckx** [comment]
You can import the library with Gradle (probably Maven too).

```
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile "com.github.benckx:ouistiti:1.1"
}
```

**Comment by RayanFar** [comment]
it's not straight forward, I can't do it, can you please convert it to java?
https://stackoverflow.com/questions/34957430/how-to-convert-a-kotlin-source-file-to-a-java-source-file

**Comment by benckx** [comment]
I created a sample Java project: https://github.com/benckx/ouistiti-sample

Build with Gradle (Linux):
```
./gradlew clean build 
```

And then run ```TestCameraManagerJava``` in IntelliJ or something.

I'm not going to re-write this in Java. The point of Kotlin is to not write Java anymore.

**Comment by benckx** [comment]
Did you manage to run the sample project?

**Comment by RayanFar** [comment]
🖕😒

**Comment by RayanFar** [comment]
🖕😒
